# ============ Aplicación ============
spring.application.name=profile
server.port=${SERVER_PORT:8083}

# ============ Base de datos PostgreSQL ============
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/profile_service}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============ JPA / Hibernate ============
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# ============ Logging ============
logging.level.edu.eci.arsw.royalarena.profile=${LOG_LEVEL:INFO}
logging.level.org.hibernate.SQL=WARN

# ============ RabbitMQ ============
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# Topología: la cola es MÍA, el exchange lo comparto con el productor
royalarena.events.exchange=royalarena.matches
royalarena.events.queue.match-finished=profile.match-finished
royalarena.events.routing-key.match-finished=match.finished